name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install GeoDjango Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install binutils libproj-dev gdal-bin -y

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
      working-directory: .

    - name: Run Migrations
      run: |
        python manage.py migrate
      working-directory: .

    - name: Run Tests
      run: |
        python manage.py test
      working-directory: .
